// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.linux:
        return linux;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFmYUYnBkIO4DuYshNhY9Ii4Vesk0tBIQ',
    appId: '1:952927490252:android:807e5b2ee9e0659554b269',
    messagingSenderId: '952927490252',
    projectId: 'dbbb-42456',
    storageBucket: 'dbbb-42456.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAFmYUYnBkIO4DuYshNhY9Ii4Vesk0tBIQ',
    appId: '1:952927490252:android:807e5b2ee9e0659554b269',
    messagingSenderId: '952927490252',
    projectId: 'dbbb-42456',
    storageBucket: 'dbbb-42456.firebasestorage.app',
  );
}
